// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { loginForAccessTokenTokenPost, type Options, readUsersMeMeGet, registerUserRegisterPost, startConcertConcertsStartPost, uploadFileConcertsUploadPost } from '../sdk.gen';
import type { LoginForAccessTokenTokenPostData, LoginForAccessTokenTokenPostError, LoginForAccessTokenTokenPostResponse, ReadUsersMeMeGetData, RegisterUserRegisterPostData, RegisterUserRegisterPostError, RegisterUserRegisterPostResponse, StartConcertConcertsStartPostData, UploadFileConcertsUploadPostData, UploadFileConcertsUploadPostError } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const readUsersMeMeGetQueryKey = (options?: Options<ReadUsersMeMeGetData>) => createQueryKey('readUsersMeMeGet', options);

/**
 * Read Users Me
 */
export const readUsersMeMeGetOptions = (options?: Options<ReadUsersMeMeGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await readUsersMeMeGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: readUsersMeMeGetQueryKey(options)
    });
};

/**
 * Register User
 */
export const registerUserRegisterPostMutation = (options?: Partial<Options<RegisterUserRegisterPostData>>): UseMutationOptions<RegisterUserRegisterPostResponse, RegisterUserRegisterPostError, Options<RegisterUserRegisterPostData>> => {
    const mutationOptions: UseMutationOptions<RegisterUserRegisterPostResponse, RegisterUserRegisterPostError, Options<RegisterUserRegisterPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await registerUserRegisterPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Login For Access Token
 */
export const loginForAccessTokenTokenPostMutation = (options?: Partial<Options<LoginForAccessTokenTokenPostData>>): UseMutationOptions<LoginForAccessTokenTokenPostResponse, LoginForAccessTokenTokenPostError, Options<LoginForAccessTokenTokenPostData>> => {
    const mutationOptions: UseMutationOptions<LoginForAccessTokenTokenPostResponse, LoginForAccessTokenTokenPostError, Options<LoginForAccessTokenTokenPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await loginForAccessTokenTokenPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Upload File
 */
export const uploadFileConcertsUploadPostMutation = (options?: Partial<Options<UploadFileConcertsUploadPostData>>): UseMutationOptions<unknown, UploadFileConcertsUploadPostError, Options<UploadFileConcertsUploadPostData>> => {
    const mutationOptions: UseMutationOptions<unknown, UploadFileConcertsUploadPostError, Options<UploadFileConcertsUploadPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await uploadFileConcertsUploadPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Start Concert
 */
export const startConcertConcertsStartPostMutation = (options?: Partial<Options<StartConcertConcertsStartPostData>>): UseMutationOptions<unknown, DefaultError, Options<StartConcertConcertsStartPostData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<StartConcertConcertsStartPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await startConcertConcertsStartPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
