// This file is auto-generated by @hey-api/openapi-ts

import { type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { createConcertConcertsCreatePost, discoverConcertsConcertsDiscoverGet, getConcertConcertsConcertIdGet, loginForAccessTokenTokenPost, type Options, readUsersMeMeGet, registerUserRegisterPost, startConcertConcertsStartConcertIdPost, stopConcertConcertsStopConcertIdPost, uploadFileConcertsUploadConcertIdPost } from '../sdk.gen';
import type { CreateConcertConcertsCreatePostData, CreateConcertConcertsCreatePostError, CreateConcertConcertsCreatePostResponse, DiscoverConcertsConcertsDiscoverGetData, DiscoverConcertsConcertsDiscoverGetError, DiscoverConcertsConcertsDiscoverGetResponse, GetConcertConcertsConcertIdGetData, LoginForAccessTokenTokenPostData, LoginForAccessTokenTokenPostError, LoginForAccessTokenTokenPostResponse, ReadUsersMeMeGetData, RegisterUserRegisterPostData, RegisterUserRegisterPostError, RegisterUserRegisterPostResponse, StartConcertConcertsStartConcertIdPostData, StartConcertConcertsStartConcertIdPostError, StopConcertConcertsStopConcertIdPostData, StopConcertConcertsStopConcertIdPostError, UploadFileConcertsUploadConcertIdPostData, UploadFileConcertsUploadConcertIdPostError } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const readUsersMeMeGetQueryKey = (options?: Options<ReadUsersMeMeGetData>) => createQueryKey('readUsersMeMeGet', options);

/**
 * Read Users Me
 */
export const readUsersMeMeGetOptions = (options?: Options<ReadUsersMeMeGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await readUsersMeMeGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: readUsersMeMeGetQueryKey(options)
    });
};

/**
 * Register User
 */
export const registerUserRegisterPostMutation = (options?: Partial<Options<RegisterUserRegisterPostData>>): UseMutationOptions<RegisterUserRegisterPostResponse, RegisterUserRegisterPostError, Options<RegisterUserRegisterPostData>> => {
    const mutationOptions: UseMutationOptions<RegisterUserRegisterPostResponse, RegisterUserRegisterPostError, Options<RegisterUserRegisterPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await registerUserRegisterPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Login For Access Token
 */
export const loginForAccessTokenTokenPostMutation = (options?: Partial<Options<LoginForAccessTokenTokenPostData>>): UseMutationOptions<LoginForAccessTokenTokenPostResponse, LoginForAccessTokenTokenPostError, Options<LoginForAccessTokenTokenPostData>> => {
    const mutationOptions: UseMutationOptions<LoginForAccessTokenTokenPostResponse, LoginForAccessTokenTokenPostError, Options<LoginForAccessTokenTokenPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await loginForAccessTokenTokenPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Upload File
 */
export const uploadFileConcertsUploadConcertIdPostMutation = (options?: Partial<Options<UploadFileConcertsUploadConcertIdPostData>>): UseMutationOptions<unknown, UploadFileConcertsUploadConcertIdPostError, Options<UploadFileConcertsUploadConcertIdPostData>> => {
    const mutationOptions: UseMutationOptions<unknown, UploadFileConcertsUploadConcertIdPostError, Options<UploadFileConcertsUploadConcertIdPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await uploadFileConcertsUploadConcertIdPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Start Concert
 */
export const startConcertConcertsStartConcertIdPostMutation = (options?: Partial<Options<StartConcertConcertsStartConcertIdPostData>>): UseMutationOptions<unknown, StartConcertConcertsStartConcertIdPostError, Options<StartConcertConcertsStartConcertIdPostData>> => {
    const mutationOptions: UseMutationOptions<unknown, StartConcertConcertsStartConcertIdPostError, Options<StartConcertConcertsStartConcertIdPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await startConcertConcertsStartConcertIdPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Stop Concert
 */
export const stopConcertConcertsStopConcertIdPostMutation = (options?: Partial<Options<StopConcertConcertsStopConcertIdPostData>>): UseMutationOptions<unknown, StopConcertConcertsStopConcertIdPostError, Options<StopConcertConcertsStopConcertIdPostData>> => {
    const mutationOptions: UseMutationOptions<unknown, StopConcertConcertsStopConcertIdPostError, Options<StopConcertConcertsStopConcertIdPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await stopConcertConcertsStopConcertIdPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Create Concert
 */
export const createConcertConcertsCreatePostMutation = (options?: Partial<Options<CreateConcertConcertsCreatePostData>>): UseMutationOptions<CreateConcertConcertsCreatePostResponse, CreateConcertConcertsCreatePostError, Options<CreateConcertConcertsCreatePostData>> => {
    const mutationOptions: UseMutationOptions<CreateConcertConcertsCreatePostResponse, CreateConcertConcertsCreatePostError, Options<CreateConcertConcertsCreatePostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createConcertConcertsCreatePost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const discoverConcertsConcertsDiscoverGetQueryKey = (options?: Options<DiscoverConcertsConcertsDiscoverGetData>) => createQueryKey('discoverConcertsConcertsDiscoverGet', options);

/**
 * Discover Concerts
 */
export const discoverConcertsConcertsDiscoverGetOptions = (options?: Options<DiscoverConcertsConcertsDiscoverGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await discoverConcertsConcertsDiscoverGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: discoverConcertsConcertsDiscoverGetQueryKey(options)
    });
};

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = {
        ...queryKey[0]
    };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const discoverConcertsConcertsDiscoverGetInfiniteQueryKey = (options?: Options<DiscoverConcertsConcertsDiscoverGetData>): QueryKey<Options<DiscoverConcertsConcertsDiscoverGetData>> => createQueryKey('discoverConcertsConcertsDiscoverGet', options, true);

/**
 * Discover Concerts
 */
export const discoverConcertsConcertsDiscoverGetInfiniteOptions = (options?: Options<DiscoverConcertsConcertsDiscoverGetData>) => {
    return infiniteQueryOptions<DiscoverConcertsConcertsDiscoverGetResponse, DiscoverConcertsConcertsDiscoverGetError, InfiniteData<DiscoverConcertsConcertsDiscoverGetResponse>, QueryKey<Options<DiscoverConcertsConcertsDiscoverGetData>>, number | Pick<QueryKey<Options<DiscoverConcertsConcertsDiscoverGetData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<DiscoverConcertsConcertsDiscoverGetData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    offset: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await discoverConcertsConcertsDiscoverGet({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: discoverConcertsConcertsDiscoverGetInfiniteQueryKey(options)
    });
};

export const getConcertConcertsConcertIdGetQueryKey = (options: Options<GetConcertConcertsConcertIdGetData>) => createQueryKey('getConcertConcertsConcertIdGet', options);

/**
 * Get Concert
 */
export const getConcertConcertsConcertIdGetOptions = (options: Options<GetConcertConcertsConcertIdGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getConcertConcertsConcertIdGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getConcertConcertsConcertIdGetQueryKey(options)
    });
};
