// This file is auto-generated by @hey-api/openapi-ts

import { type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { createConcertConcertsCreatePost, createSetlistItemConcertsConcertIdSetlistPost, deleteConcertConcertsConcertIdDelete, deleteMediaArtistsMediaAssetIdDelete, deleteSetlistItemConcertsConcertIdSetlistItemIdDelete, discoverConcertsConcertsDiscoverGet, getConcertConcertsConcertIdGet, listMediaArtistsMediaGet, loginUserTokenPost, type Options, readUsersMeMeGet, registerUserRegisterPost, updateConcertConcertsConcertIdPatch, uploadConcertImageConcertsConcertIdImagePost, uploadMediaArtistsMediaPost } from '../sdk.gen';
import type { CreateConcertConcertsCreatePostData, CreateConcertConcertsCreatePostError, CreateConcertConcertsCreatePostResponse, CreateSetlistItemConcertsConcertIdSetlistPostData, CreateSetlistItemConcertsConcertIdSetlistPostError, CreateSetlistItemConcertsConcertIdSetlistPostResponse, DeleteConcertConcertsConcertIdDeleteData, DeleteConcertConcertsConcertIdDeleteError, DeleteConcertConcertsConcertIdDeleteResponse, DeleteMediaArtistsMediaAssetIdDeleteData, DeleteMediaArtistsMediaAssetIdDeleteError, DeleteMediaArtistsMediaAssetIdDeleteResponse, DeleteSetlistItemConcertsConcertIdSetlistItemIdDeleteData, DeleteSetlistItemConcertsConcertIdSetlistItemIdDeleteError, DeleteSetlistItemConcertsConcertIdSetlistItemIdDeleteResponse, DiscoverConcertsConcertsDiscoverGetData, DiscoverConcertsConcertsDiscoverGetError, DiscoverConcertsConcertsDiscoverGetResponse, GetConcertConcertsConcertIdGetData, ListMediaArtistsMediaGetData, ListMediaArtistsMediaGetError, ListMediaArtistsMediaGetResponse, LoginUserTokenPostData, LoginUserTokenPostError, ReadUsersMeMeGetData, RegisterUserRegisterPostData, RegisterUserRegisterPostError, RegisterUserRegisterPostResponse, UpdateConcertConcertsConcertIdPatchData, UpdateConcertConcertsConcertIdPatchError, UpdateConcertConcertsConcertIdPatchResponse, UploadConcertImageConcertsConcertIdImagePostData, UploadConcertImageConcertsConcertIdImagePostError, UploadConcertImageConcertsConcertIdImagePostResponse, UploadMediaArtistsMediaPostData, UploadMediaArtistsMediaPostError, UploadMediaArtistsMediaPostResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const readUsersMeMeGetQueryKey = (options?: Options<ReadUsersMeMeGetData>) => createQueryKey('readUsersMeMeGet', options);

/**
 * Read Users Me
 */
export const readUsersMeMeGetOptions = (options?: Options<ReadUsersMeMeGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await readUsersMeMeGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: readUsersMeMeGetQueryKey(options)
    });
};

/**
 * Login User
 */
export const loginUserTokenPostMutation = (options?: Partial<Options<LoginUserTokenPostData>>): UseMutationOptions<unknown, LoginUserTokenPostError, Options<LoginUserTokenPostData>> => {
    const mutationOptions: UseMutationOptions<unknown, LoginUserTokenPostError, Options<LoginUserTokenPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await loginUserTokenPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Register User
 */
export const registerUserRegisterPostMutation = (options?: Partial<Options<RegisterUserRegisterPostData>>): UseMutationOptions<RegisterUserRegisterPostResponse, RegisterUserRegisterPostError, Options<RegisterUserRegisterPostData>> => {
    const mutationOptions: UseMutationOptions<RegisterUserRegisterPostResponse, RegisterUserRegisterPostError, Options<RegisterUserRegisterPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await registerUserRegisterPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Upload Concert Image
 */
export const uploadConcertImageConcertsConcertIdImagePostMutation = (options?: Partial<Options<UploadConcertImageConcertsConcertIdImagePostData>>): UseMutationOptions<UploadConcertImageConcertsConcertIdImagePostResponse, UploadConcertImageConcertsConcertIdImagePostError, Options<UploadConcertImageConcertsConcertIdImagePostData>> => {
    const mutationOptions: UseMutationOptions<UploadConcertImageConcertsConcertIdImagePostResponse, UploadConcertImageConcertsConcertIdImagePostError, Options<UploadConcertImageConcertsConcertIdImagePostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await uploadConcertImageConcertsConcertIdImagePost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Create Concert
 */
export const createConcertConcertsCreatePostMutation = (options?: Partial<Options<CreateConcertConcertsCreatePostData>>): UseMutationOptions<CreateConcertConcertsCreatePostResponse, CreateConcertConcertsCreatePostError, Options<CreateConcertConcertsCreatePostData>> => {
    const mutationOptions: UseMutationOptions<CreateConcertConcertsCreatePostResponse, CreateConcertConcertsCreatePostError, Options<CreateConcertConcertsCreatePostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createConcertConcertsCreatePost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const discoverConcertsConcertsDiscoverGetQueryKey = (options?: Options<DiscoverConcertsConcertsDiscoverGetData>) => createQueryKey('discoverConcertsConcertsDiscoverGet', options);

/**
 * Discover Concerts
 */
export const discoverConcertsConcertsDiscoverGetOptions = (options?: Options<DiscoverConcertsConcertsDiscoverGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await discoverConcertsConcertsDiscoverGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: discoverConcertsConcertsDiscoverGetQueryKey(options)
    });
};

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = {
        ...queryKey[0]
    };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const discoverConcertsConcertsDiscoverGetInfiniteQueryKey = (options?: Options<DiscoverConcertsConcertsDiscoverGetData>): QueryKey<Options<DiscoverConcertsConcertsDiscoverGetData>> => createQueryKey('discoverConcertsConcertsDiscoverGet', options, true);

/**
 * Discover Concerts
 */
export const discoverConcertsConcertsDiscoverGetInfiniteOptions = (options?: Options<DiscoverConcertsConcertsDiscoverGetData>) => {
    return infiniteQueryOptions<DiscoverConcertsConcertsDiscoverGetResponse, DiscoverConcertsConcertsDiscoverGetError, InfiniteData<DiscoverConcertsConcertsDiscoverGetResponse>, QueryKey<Options<DiscoverConcertsConcertsDiscoverGetData>>, number | Pick<QueryKey<Options<DiscoverConcertsConcertsDiscoverGetData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<DiscoverConcertsConcertsDiscoverGetData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    offset: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await discoverConcertsConcertsDiscoverGet({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: discoverConcertsConcertsDiscoverGetInfiniteQueryKey(options)
    });
};

/**
 * Delete Concert
 */
export const deleteConcertConcertsConcertIdDeleteMutation = (options?: Partial<Options<DeleteConcertConcertsConcertIdDeleteData>>): UseMutationOptions<DeleteConcertConcertsConcertIdDeleteResponse, DeleteConcertConcertsConcertIdDeleteError, Options<DeleteConcertConcertsConcertIdDeleteData>> => {
    const mutationOptions: UseMutationOptions<DeleteConcertConcertsConcertIdDeleteResponse, DeleteConcertConcertsConcertIdDeleteError, Options<DeleteConcertConcertsConcertIdDeleteData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteConcertConcertsConcertIdDelete({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getConcertConcertsConcertIdGetQueryKey = (options: Options<GetConcertConcertsConcertIdGetData>) => createQueryKey('getConcertConcertsConcertIdGet', options);

/**
 * Get Concert
 */
export const getConcertConcertsConcertIdGetOptions = (options: Options<GetConcertConcertsConcertIdGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getConcertConcertsConcertIdGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getConcertConcertsConcertIdGetQueryKey(options)
    });
};

/**
 * Update Concert
 */
export const updateConcertConcertsConcertIdPatchMutation = (options?: Partial<Options<UpdateConcertConcertsConcertIdPatchData>>): UseMutationOptions<UpdateConcertConcertsConcertIdPatchResponse, UpdateConcertConcertsConcertIdPatchError, Options<UpdateConcertConcertsConcertIdPatchData>> => {
    const mutationOptions: UseMutationOptions<UpdateConcertConcertsConcertIdPatchResponse, UpdateConcertConcertsConcertIdPatchError, Options<UpdateConcertConcertsConcertIdPatchData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateConcertConcertsConcertIdPatch({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Create Setlist Item
 */
export const createSetlistItemConcertsConcertIdSetlistPostMutation = (options?: Partial<Options<CreateSetlistItemConcertsConcertIdSetlistPostData>>): UseMutationOptions<CreateSetlistItemConcertsConcertIdSetlistPostResponse, CreateSetlistItemConcertsConcertIdSetlistPostError, Options<CreateSetlistItemConcertsConcertIdSetlistPostData>> => {
    const mutationOptions: UseMutationOptions<CreateSetlistItemConcertsConcertIdSetlistPostResponse, CreateSetlistItemConcertsConcertIdSetlistPostError, Options<CreateSetlistItemConcertsConcertIdSetlistPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createSetlistItemConcertsConcertIdSetlistPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete Setlist Item
 */
export const deleteSetlistItemConcertsConcertIdSetlistItemIdDeleteMutation = (options?: Partial<Options<DeleteSetlistItemConcertsConcertIdSetlistItemIdDeleteData>>): UseMutationOptions<DeleteSetlistItemConcertsConcertIdSetlistItemIdDeleteResponse, DeleteSetlistItemConcertsConcertIdSetlistItemIdDeleteError, Options<DeleteSetlistItemConcertsConcertIdSetlistItemIdDeleteData>> => {
    const mutationOptions: UseMutationOptions<DeleteSetlistItemConcertsConcertIdSetlistItemIdDeleteResponse, DeleteSetlistItemConcertsConcertIdSetlistItemIdDeleteError, Options<DeleteSetlistItemConcertsConcertIdSetlistItemIdDeleteData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteSetlistItemConcertsConcertIdSetlistItemIdDelete({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listMediaArtistsMediaGetQueryKey = (options?: Options<ListMediaArtistsMediaGetData>) => createQueryKey('listMediaArtistsMediaGet', options);

/**
 * List Media
 */
export const listMediaArtistsMediaGetOptions = (options?: Options<ListMediaArtistsMediaGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await listMediaArtistsMediaGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: listMediaArtistsMediaGetQueryKey(options)
    });
};

export const listMediaArtistsMediaGetInfiniteQueryKey = (options?: Options<ListMediaArtistsMediaGetData>): QueryKey<Options<ListMediaArtistsMediaGetData>> => createQueryKey('listMediaArtistsMediaGet', options, true);

/**
 * List Media
 */
export const listMediaArtistsMediaGetInfiniteOptions = (options?: Options<ListMediaArtistsMediaGetData>) => {
    return infiniteQueryOptions<ListMediaArtistsMediaGetResponse, ListMediaArtistsMediaGetError, InfiniteData<ListMediaArtistsMediaGetResponse>, QueryKey<Options<ListMediaArtistsMediaGetData>>, number | Pick<QueryKey<Options<ListMediaArtistsMediaGetData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<ListMediaArtistsMediaGetData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    offset: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await listMediaArtistsMediaGet({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: listMediaArtistsMediaGetInfiniteQueryKey(options)
    });
};

/**
 * Upload Media
 */
export const uploadMediaArtistsMediaPostMutation = (options?: Partial<Options<UploadMediaArtistsMediaPostData>>): UseMutationOptions<UploadMediaArtistsMediaPostResponse, UploadMediaArtistsMediaPostError, Options<UploadMediaArtistsMediaPostData>> => {
    const mutationOptions: UseMutationOptions<UploadMediaArtistsMediaPostResponse, UploadMediaArtistsMediaPostError, Options<UploadMediaArtistsMediaPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await uploadMediaArtistsMediaPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete Media
 */
export const deleteMediaArtistsMediaAssetIdDeleteMutation = (options?: Partial<Options<DeleteMediaArtistsMediaAssetIdDeleteData>>): UseMutationOptions<DeleteMediaArtistsMediaAssetIdDeleteResponse, DeleteMediaArtistsMediaAssetIdDeleteError, Options<DeleteMediaArtistsMediaAssetIdDeleteData>> => {
    const mutationOptions: UseMutationOptions<DeleteMediaArtistsMediaAssetIdDeleteResponse, DeleteMediaArtistsMediaAssetIdDeleteError, Options<DeleteMediaArtistsMediaAssetIdDeleteData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteMediaArtistsMediaAssetIdDelete({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
