// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape, urlSearchParamsBodySerializer } from './client';
import { client } from './client.gen';
import type { CreateConcertConcertsCreatePostData, CreateConcertConcertsCreatePostErrors, CreateConcertConcertsCreatePostResponses, DeleteConcertConcertsConcertIdDeleteData, DeleteConcertConcertsConcertIdDeleteErrors, DeleteConcertConcertsConcertIdDeleteResponses, DiscoverConcertsConcertsDiscoverGetData, DiscoverConcertsConcertsDiscoverGetErrors, DiscoverConcertsConcertsDiscoverGetResponses, GetConcertConcertsConcertIdGetData, GetConcertConcertsConcertIdGetErrors, GetConcertConcertsConcertIdGetResponses, LoginUserTokenPostData, LoginUserTokenPostErrors, LoginUserTokenPostResponses, ReadUsersMeMeGetData, ReadUsersMeMeGetErrors, ReadUsersMeMeGetResponses, RegisterUserRegisterPostData, RegisterUserRegisterPostErrors, RegisterUserRegisterPostResponses, UpdateConcertConcertsConcertIdPatchData, UpdateConcertConcertsConcertIdPatchErrors, UpdateConcertConcertsConcertIdPatchResponses, UploadConcertImageConcertsUploadImageConcertIdPostData, UploadConcertImageConcertsUploadImageConcertIdPostErrors, UploadConcertImageConcertsUploadImageConcertIdPostResponses, UploadSongConcertsUploadSongConcertIdPostData, UploadSongConcertsUploadSongConcertIdPostErrors, UploadSongConcertsUploadSongConcertIdPostResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Read Users Me
 */
export const readUsersMeMeGet = <ThrowOnError extends boolean = false>(options?: Options<ReadUsersMeMeGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<ReadUsersMeMeGetResponses, ReadUsersMeMeGetErrors, ThrowOnError>({
        url: '/me',
        ...options
    });
};

/**
 * Login User
 */
export const loginUserTokenPost = <ThrowOnError extends boolean = false>(options: Options<LoginUserTokenPostData, ThrowOnError>) => {
    return (options.client ?? client).post<LoginUserTokenPostResponses, LoginUserTokenPostErrors, ThrowOnError>({
        ...urlSearchParamsBodySerializer,
        url: '/token',
        ...options,
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
            ...options.headers
        }
    });
};

/**
 * Register User
 */
export const registerUserRegisterPost = <ThrowOnError extends boolean = false>(options: Options<RegisterUserRegisterPostData, ThrowOnError>) => {
    return (options.client ?? client).post<RegisterUserRegisterPostResponses, RegisterUserRegisterPostErrors, ThrowOnError>({
        url: '/register',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Upload Concert Image
 */
export const uploadConcertImageConcertsUploadImageConcertIdPost = <ThrowOnError extends boolean = false>(options: Options<UploadConcertImageConcertsUploadImageConcertIdPostData, ThrowOnError>) => {
    return (options.client ?? client).post<UploadConcertImageConcertsUploadImageConcertIdPostResponses, UploadConcertImageConcertsUploadImageConcertIdPostErrors, ThrowOnError>({
        ...formDataBodySerializer,
        url: '/concerts/upload-image/{concert_id}',
        ...options,
        headers: {
            'Content-Type': null,
            ...options.headers
        }
    });
};

/**
 * Upload Song
 */
export const uploadSongConcertsUploadSongConcertIdPost = <ThrowOnError extends boolean = false>(options: Options<UploadSongConcertsUploadSongConcertIdPostData, ThrowOnError>) => {
    return (options.client ?? client).post<UploadSongConcertsUploadSongConcertIdPostResponses, UploadSongConcertsUploadSongConcertIdPostErrors, ThrowOnError>({
        ...formDataBodySerializer,
        url: '/concerts/upload-song/{concert_id}',
        ...options,
        headers: {
            'Content-Type': null,
            ...options.headers
        }
    });
};

/**
 * Create Concert
 */
export const createConcertConcertsCreatePost = <ThrowOnError extends boolean = false>(options?: Options<CreateConcertConcertsCreatePostData, ThrowOnError>) => {
    return (options?.client ?? client).post<CreateConcertConcertsCreatePostResponses, CreateConcertConcertsCreatePostErrors, ThrowOnError>({
        url: '/concerts/create',
        ...options
    });
};

/**
 * Discover Concerts
 */
export const discoverConcertsConcertsDiscoverGet = <ThrowOnError extends boolean = false>(options?: Options<DiscoverConcertsConcertsDiscoverGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<DiscoverConcertsConcertsDiscoverGetResponses, DiscoverConcertsConcertsDiscoverGetErrors, ThrowOnError>({
        url: '/concerts/discover',
        ...options
    });
};

/**
 * Delete Concert
 */
export const deleteConcertConcertsConcertIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteConcertConcertsConcertIdDeleteData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteConcertConcertsConcertIdDeleteResponses, DeleteConcertConcertsConcertIdDeleteErrors, ThrowOnError>({
        url: '/concerts/{concert_id}',
        ...options
    });
};

/**
 * Get Concert
 */
export const getConcertConcertsConcertIdGet = <ThrowOnError extends boolean = false>(options: Options<GetConcertConcertsConcertIdGetData, ThrowOnError>) => {
    return (options.client ?? client).get<GetConcertConcertsConcertIdGetResponses, GetConcertConcertsConcertIdGetErrors, ThrowOnError>({
        url: '/concerts/{concert_id}',
        ...options
    });
};

/**
 * Update Concert
 */
export const updateConcertConcertsConcertIdPatch = <ThrowOnError extends boolean = false>(options: Options<UpdateConcertConcertsConcertIdPatchData, ThrowOnError>) => {
    return (options.client ?? client).patch<UpdateConcertConcertsConcertIdPatchResponses, UpdateConcertConcertsConcertIdPatchErrors, ThrowOnError>({
        url: '/concerts/{concert_id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};
