// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape, urlSearchParamsBodySerializer } from './client';
import { client } from './client.gen';
import type { CreateConcertConcertsCreatePostData, CreateConcertConcertsCreatePostErrors, CreateConcertConcertsCreatePostResponses, DeleteConcertConcertsConcertIdDeleteData, DeleteConcertConcertsConcertIdDeleteErrors, DeleteConcertConcertsConcertIdDeleteResponses, DiscoverConcertsConcertsDiscoverGetData, DiscoverConcertsConcertsDiscoverGetErrors, DiscoverConcertsConcertsDiscoverGetResponses, GetConcertConcertsConcertIdGetData, GetConcertConcertsConcertIdGetErrors, GetConcertConcertsConcertIdGetResponses, LoginForAccessTokenTokenPostData, LoginForAccessTokenTokenPostErrors, LoginForAccessTokenTokenPostResponses, ReadUsersMeMeGetData, ReadUsersMeMeGetResponses, RegisterUserRegisterPostData, RegisterUserRegisterPostErrors, RegisterUserRegisterPostResponses, StartConcertConcertsStartConcertIdPostData, StartConcertConcertsStartConcertIdPostErrors, StartConcertConcertsStartConcertIdPostResponses, StopConcertConcertsStopConcertIdPostData, StopConcertConcertsStopConcertIdPostErrors, StopConcertConcertsStopConcertIdPostResponses, UpdateConcertConcertsConcertIdPatchData, UpdateConcertConcertsConcertIdPatchErrors, UpdateConcertConcertsConcertIdPatchResponses, UploadConcertImageConcertsUploadImageConcertIdPostData, UploadConcertImageConcertsUploadImageConcertIdPostErrors, UploadConcertImageConcertsUploadImageConcertIdPostResponses, UploadFileConcertsUploadSongConcertIdPostData, UploadFileConcertsUploadSongConcertIdPostErrors, UploadFileConcertsUploadSongConcertIdPostResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Read Users Me
 */
export const readUsersMeMeGet = <ThrowOnError extends boolean = false>(options?: Options<ReadUsersMeMeGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<ReadUsersMeMeGetResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/me',
        ...options
    });
};

/**
 * Register User
 */
export const registerUserRegisterPost = <ThrowOnError extends boolean = false>(options: Options<RegisterUserRegisterPostData, ThrowOnError>) => {
    return (options.client ?? client).post<RegisterUserRegisterPostResponses, RegisterUserRegisterPostErrors, ThrowOnError>({
        url: '/register',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Login For Access Token
 */
export const loginForAccessTokenTokenPost = <ThrowOnError extends boolean = false>(options: Options<LoginForAccessTokenTokenPostData, ThrowOnError>) => {
    return (options.client ?? client).post<LoginForAccessTokenTokenPostResponses, LoginForAccessTokenTokenPostErrors, ThrowOnError>({
        ...urlSearchParamsBodySerializer,
        url: '/token',
        ...options,
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
            ...options.headers
        }
    });
};

/**
 * Upload Concert Image
 */
export const uploadConcertImageConcertsUploadImageConcertIdPost = <ThrowOnError extends boolean = false>(options: Options<UploadConcertImageConcertsUploadImageConcertIdPostData, ThrowOnError>) => {
    return (options.client ?? client).post<UploadConcertImageConcertsUploadImageConcertIdPostResponses, UploadConcertImageConcertsUploadImageConcertIdPostErrors, ThrowOnError>({
        ...formDataBodySerializer,
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/concerts/upload-image/{concert_id}',
        ...options,
        headers: {
            'Content-Type': null,
            ...options.headers
        }
    });
};

/**
 * Upload File
 */
export const uploadFileConcertsUploadSongConcertIdPost = <ThrowOnError extends boolean = false>(options: Options<UploadFileConcertsUploadSongConcertIdPostData, ThrowOnError>) => {
    return (options.client ?? client).post<UploadFileConcertsUploadSongConcertIdPostResponses, UploadFileConcertsUploadSongConcertIdPostErrors, ThrowOnError>({
        ...formDataBodySerializer,
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/concerts/upload-song/{concert_id}',
        ...options,
        headers: {
            'Content-Type': null,
            ...options.headers
        }
    });
};

/**
 * Start Concert
 */
export const startConcertConcertsStartConcertIdPost = <ThrowOnError extends boolean = false>(options: Options<StartConcertConcertsStartConcertIdPostData, ThrowOnError>) => {
    return (options.client ?? client).post<StartConcertConcertsStartConcertIdPostResponses, StartConcertConcertsStartConcertIdPostErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/concerts/start/{concert_id}',
        ...options
    });
};

/**
 * Stop Concert
 */
export const stopConcertConcertsStopConcertIdPost = <ThrowOnError extends boolean = false>(options: Options<StopConcertConcertsStopConcertIdPostData, ThrowOnError>) => {
    return (options.client ?? client).post<StopConcertConcertsStopConcertIdPostResponses, StopConcertConcertsStopConcertIdPostErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/concerts/stop/{concert_id}',
        ...options
    });
};

/**
 * Create Concert
 */
export const createConcertConcertsCreatePost = <ThrowOnError extends boolean = false>(options: Options<CreateConcertConcertsCreatePostData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateConcertConcertsCreatePostResponses, CreateConcertConcertsCreatePostErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/concerts/create',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Discover Concerts
 */
export const discoverConcertsConcertsDiscoverGet = <ThrowOnError extends boolean = false>(options?: Options<DiscoverConcertsConcertsDiscoverGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<DiscoverConcertsConcertsDiscoverGetResponses, DiscoverConcertsConcertsDiscoverGetErrors, ThrowOnError>({
        url: '/concerts/discover',
        ...options
    });
};

/**
 * Delete Concert
 */
export const deleteConcertConcertsConcertIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteConcertConcertsConcertIdDeleteData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteConcertConcertsConcertIdDeleteResponses, DeleteConcertConcertsConcertIdDeleteErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/concerts/{concert_id}',
        ...options
    });
};

/**
 * Get Concert
 */
export const getConcertConcertsConcertIdGet = <ThrowOnError extends boolean = false>(options: Options<GetConcertConcertsConcertIdGetData, ThrowOnError>) => {
    return (options.client ?? client).get<GetConcertConcertsConcertIdGetResponses, GetConcertConcertsConcertIdGetErrors, ThrowOnError>({
        url: '/concerts/{concert_id}',
        ...options
    });
};

/**
 * Update Concert
 */
export const updateConcertConcertsConcertIdPatch = <ThrowOnError extends boolean = false>(options: Options<UpdateConcertConcertsConcertIdPatchData, ThrowOnError>) => {
    return (options.client ?? client).patch<UpdateConcertConcertsConcertIdPatchResponses, UpdateConcertConcertsConcertIdPatchErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/concerts/{concert_id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};
