// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://openapi.json` | (string & {});
};

/**
 * ArtistPublic
 */
export type ArtistPublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Id
     */
    id: number;
};

/**
 * Body_login_for_access_token_token_post
 */
export type BodyLoginForAccessTokenTokenPost = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * Body_upload_concert_image_concerts_upload_image__concert_id__post
 */
export type BodyUploadConcertImageConcertsUploadImageConcertIdPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_upload_file_concerts_upload_song__concert_id__post
 */
export type BodyUploadFileConcertsUploadSongConcertIdPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * ConcertBase
 */
export type ConcertBase = {
    /**
     * Name
     */
    name: string;
    /**
     * Start Time
     */
    start_time: string;
    /**
     * Max Capacity
     */
    max_capacity?: number;
    /**
     * Ticket Price
     */
    ticket_price: number;
    /**
     * Description
     */
    description?: string;
    /**
     * Cover Image Url
     */
    cover_image_url?: string | null;
};

/**
 * ConcertPublic
 */
export type ConcertPublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Start Time
     */
    start_time: string;
    /**
     * Max Capacity
     */
    max_capacity?: number;
    /**
     * Ticket Price
     */
    ticket_price: number;
    /**
     * Description
     */
    description?: string;
    /**
     * Cover Image Url
     */
    cover_image_url?: string | null;
    /**
     * Id
     */
    id: number;
    artist: ArtistPublic;
};

/**
 * ConcertUpdate
 */
export type ConcertUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Start Time
     */
    start_time?: string | null;
    /**
     * Max Capacity
     */
    max_capacity?: number | null;
    /**
     * Ticket Price
     */
    ticket_price?: number | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Cover Image Url
     */
    cover_image_url?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ImageUploadResponse
 */
export type ImageUploadResponse = {
    /**
     * Cover Image Url
     */
    cover_image_url: string;
};

/**
 * PaginatedConcerts
 */
export type PaginatedConcerts = {
    /**
     * Items
     */
    items: Array<ConcertPublic>;
    /**
     * Hasmore
     */
    hasMore: boolean;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Id
     */
    id: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type ReadUsersMeMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/me';
};

export type ReadUsersMeMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type ReadUsersMeMeGetResponse = ReadUsersMeMeGetResponses[keyof ReadUsersMeMeGetResponses];

export type RegisterUserRegisterPostData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/register';
};

export type RegisterUserRegisterPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterUserRegisterPostError = RegisterUserRegisterPostErrors[keyof RegisterUserRegisterPostErrors];

export type RegisterUserRegisterPostResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type RegisterUserRegisterPostResponse = RegisterUserRegisterPostResponses[keyof RegisterUserRegisterPostResponses];

export type LoginForAccessTokenTokenPostData = {
    body: BodyLoginForAccessTokenTokenPost;
    path?: never;
    query?: never;
    url: '/token';
};

export type LoginForAccessTokenTokenPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginForAccessTokenTokenPostError = LoginForAccessTokenTokenPostErrors[keyof LoginForAccessTokenTokenPostErrors];

export type LoginForAccessTokenTokenPostResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginForAccessTokenTokenPostResponse = LoginForAccessTokenTokenPostResponses[keyof LoginForAccessTokenTokenPostResponses];

export type UploadConcertImageConcertsUploadImageConcertIdPostData = {
    body: BodyUploadConcertImageConcertsUploadImageConcertIdPost;
    path: {
        /**
         * Concert Id
         */
        concert_id: number;
    };
    query?: never;
    url: '/concerts/upload-image/{concert_id}';
};

export type UploadConcertImageConcertsUploadImageConcertIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadConcertImageConcertsUploadImageConcertIdPostError = UploadConcertImageConcertsUploadImageConcertIdPostErrors[keyof UploadConcertImageConcertsUploadImageConcertIdPostErrors];

export type UploadConcertImageConcertsUploadImageConcertIdPostResponses = {
    /**
     * Successful Response
     */
    200: ImageUploadResponse;
};

export type UploadConcertImageConcertsUploadImageConcertIdPostResponse = UploadConcertImageConcertsUploadImageConcertIdPostResponses[keyof UploadConcertImageConcertsUploadImageConcertIdPostResponses];

export type UploadFileConcertsUploadSongConcertIdPostData = {
    body: BodyUploadFileConcertsUploadSongConcertIdPost;
    path: {
        /**
         * Concert Id
         */
        concert_id: number;
    };
    query?: never;
    url: '/concerts/upload-song/{concert_id}';
};

export type UploadFileConcertsUploadSongConcertIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadFileConcertsUploadSongConcertIdPostError = UploadFileConcertsUploadSongConcertIdPostErrors[keyof UploadFileConcertsUploadSongConcertIdPostErrors];

export type UploadFileConcertsUploadSongConcertIdPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type StartConcertConcertsStartConcertIdPostData = {
    body?: never;
    path: {
        /**
         * Concert Id
         */
        concert_id: number;
    };
    query?: never;
    url: '/concerts/start/{concert_id}';
};

export type StartConcertConcertsStartConcertIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StartConcertConcertsStartConcertIdPostError = StartConcertConcertsStartConcertIdPostErrors[keyof StartConcertConcertsStartConcertIdPostErrors];

export type StartConcertConcertsStartConcertIdPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type StopConcertConcertsStopConcertIdPostData = {
    body?: never;
    path: {
        /**
         * Concert Id
         */
        concert_id: number;
    };
    query?: never;
    url: '/concerts/stop/{concert_id}';
};

export type StopConcertConcertsStopConcertIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StopConcertConcertsStopConcertIdPostError = StopConcertConcertsStopConcertIdPostErrors[keyof StopConcertConcertsStopConcertIdPostErrors];

export type StopConcertConcertsStopConcertIdPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateConcertConcertsCreatePostData = {
    body: ConcertBase;
    path?: never;
    query?: never;
    url: '/concerts/create';
};

export type CreateConcertConcertsCreatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateConcertConcertsCreatePostError = CreateConcertConcertsCreatePostErrors[keyof CreateConcertConcertsCreatePostErrors];

export type CreateConcertConcertsCreatePostResponses = {
    /**
     * Successful Response
     */
    200: ConcertPublic;
};

export type CreateConcertConcertsCreatePostResponse = CreateConcertConcertsCreatePostResponses[keyof CreateConcertConcertsCreatePostResponses];

export type DiscoverConcertsConcertsDiscoverGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
        /**
         * Sort By
         *
         * Sort order
         */
        sort_by?: 'upcoming' | 'popularity';
    };
    url: '/concerts/discover';
};

export type DiscoverConcertsConcertsDiscoverGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DiscoverConcertsConcertsDiscoverGetError = DiscoverConcertsConcertsDiscoverGetErrors[keyof DiscoverConcertsConcertsDiscoverGetErrors];

export type DiscoverConcertsConcertsDiscoverGetResponses = {
    /**
     * Successful Response
     */
    200: PaginatedConcerts;
};

export type DiscoverConcertsConcertsDiscoverGetResponse = DiscoverConcertsConcertsDiscoverGetResponses[keyof DiscoverConcertsConcertsDiscoverGetResponses];

export type DeleteConcertConcertsConcertIdDeleteData = {
    body?: never;
    path: {
        /**
         * Concert Id
         */
        concert_id: number;
    };
    query?: never;
    url: '/concerts/{concert_id}';
};

export type DeleteConcertConcertsConcertIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteConcertConcertsConcertIdDeleteError = DeleteConcertConcertsConcertIdDeleteErrors[keyof DeleteConcertConcertsConcertIdDeleteErrors];

export type DeleteConcertConcertsConcertIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteConcertConcertsConcertIdDeleteResponse = DeleteConcertConcertsConcertIdDeleteResponses[keyof DeleteConcertConcertsConcertIdDeleteResponses];

export type GetConcertConcertsConcertIdGetData = {
    body?: never;
    path: {
        /**
         * Concert Id
         */
        concert_id: number;
    };
    query?: never;
    url: '/concerts/{concert_id}';
};

export type GetConcertConcertsConcertIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetConcertConcertsConcertIdGetError = GetConcertConcertsConcertIdGetErrors[keyof GetConcertConcertsConcertIdGetErrors];

export type GetConcertConcertsConcertIdGetResponses = {
    /**
     * Successful Response
     */
    200: ConcertPublic;
};

export type GetConcertConcertsConcertIdGetResponse = GetConcertConcertsConcertIdGetResponses[keyof GetConcertConcertsConcertIdGetResponses];

export type UpdateConcertConcertsConcertIdPatchData = {
    body: ConcertUpdate;
    path: {
        /**
         * Concert Id
         */
        concert_id: number;
    };
    query?: never;
    url: '/concerts/{concert_id}';
};

export type UpdateConcertConcertsConcertIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateConcertConcertsConcertIdPatchError = UpdateConcertConcertsConcertIdPatchErrors[keyof UpdateConcertConcertsConcertIdPatchErrors];

export type UpdateConcertConcertsConcertIdPatchResponses = {
    /**
     * Successful Response
     */
    200: ConcertPublic;
};

export type UpdateConcertConcertsConcertIdPatchResponse = UpdateConcertConcertsConcertIdPatchResponses[keyof UpdateConcertConcertsConcertIdPatchResponses];
